apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pp
  janus-idp.io/tekton: pp
  backstage.io/kubernetes-id: pp
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pp
resources:
- deployment.yaml
- route.yaml
- service.yaml
