apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: pp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pp 
  name: pp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pp
    weight: 100 
